baseURL: https://blog.OwnYourGa.me/
languageCode: en-us
title: Own Your Game

theme: "PaperMod3"

menu:
    main:
        - name: Home
          url: /
          weight: 3
        - name: Posts
          url: posts/
          weight: 5
        - name: Tags
          url: tags
          weight: 10
        - name: Series
          url: series
          weight: 10


# 
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "OwnYourGame: connecting players and coaches"
    author: [OwnYourGame Staff]
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Own Your Game Blog
        imageUrl: ./batnball3.png
        imageTitle: OYG LOGO
        imageWidth: 249
        imageHeight: 164
        Content: >
            - **OwnYourGame** is a platform that connects coaches and players.

            - Coming Late 21'/Early 22'

            - This blog is a space to share opinions and expiences in coaching and player development.



        buttons:
            - name: posts 
              url: archives
            - name: Tags
              url: tags
 
    socialIcons:
        - name: instagram
          url: "https://instagram.com"
        - name: twitter
          url: "https://twitter.com"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/NickS55/oyg_blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "G-E6HRMN5WKW"

    assets:
        favicon: "./favicon.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true


deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: blog-deployment
    - URL: "s3://oyg-blog?region=us-east-1"
    - cloudFrontDistributionID: <ID>
    
  # matchers:
  #   - pattern: ^.+\.(js|css|svg|ttf)$
  #     cacheControl: 'max-age=31536000, no-transform, public'
  #     gzip: true
  #   - pattern: ^.+\.(png|jpg)$
  #     cacheControl: 'max-age=31536000, no-transform, public'
  #     gzip: false
  #   - pattern: ^sitemap\.xml$
  #     contentType: application/xml
  #     gzip: true
  #   - pattern: ^.+\.(html|xml|json)$
  #     gzip: true
